#!/usr/bin/with-contenv sh

PUID=${PUID:-911}
PGID=${PGID:-911}

if [ ! "$(id -u abc)" -eq "$PUID" ]; then usermod -o -u "$PUID" abc ; fi
if [ ! "$(id -g abc)" -eq "$PGID" ]; then groupmod -o -g "$PGID" abc ; fi

echo "
Info: GID/UID
Info: -------------------------------------
Info: User uid:    $(id -u abc)
Info: User gid:    $(id -g abc)
Info: -------------------------------------
"

chown abc:abc /apps
chown abc:abc /config
chown abc:abc /defaults
chown abc:abc /data
chown abc:abc	/var/lock/rclone.lock
